apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: default-role
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - "*"